#主配置文件，将框架需要的参数配置在此

#服务端口
server:
  port: 8080

spring:
  application:
    name: service-web
  #激活的配置文件
  profiles:
    active: test
  #数据库
  datasource:
      url: jdbc:mysql://10.128.91.198:3306/springcloud?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      username: root
      password: zaq1XSW2
      driver-class-name: com.mysql.jdbc.Driver
  #spring-boot-admin注册地址
  boot:
    admin:
      url: http://10.128.91.223:51001

#此处信息用于在spring-boot-admin中展示
info:
  app:
    name: "@project.name@"
    description: "这是一个web工程"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"




## 刷新时，关闭安全验证
management:
  security:
    enabled: false



logback:
  logdir: logs
  appname: ${spring.application.name}


feign:
  #hystrix调用fallback需要加此配置
  hystrix:
    enabled: true


