#测试环境模式

#自定义参数
BusiMDA:
  prodOfferName: abcd


#对配置路径下的redis做拦截
RedisMDA:
  pathPattern: /cache/**

# UDAL配置数据节点
ctgudal:
  datasource:
  #数据源列表ds1,ds2,ds3
    names: ds1,ds2
    ds1:
      type: jdbc
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.128.91.222:8866/testschema1?autoReconnect=true&amp;rewriteBatchedStatements=true&amp;socketTimeout=30000&amp;connectTimeout=3000
      username: dpuser1
      password: Asiainfo@123
      maxActive: 20
      minIdle: 2
      initialSize: 2
    ds2:
      type: jdbc
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.128.91.222:8866/testschema2?autoReconnect=true&amp;rewriteBatchedStatements=true&amp;socketTimeout=30000&amp;connectTimeout=3000
      username: dpuser1
      password: Asiainfo@123
    ds3:
      type: jndi
      jndiName: java:comp/env/jdbc/mysql/yxzy
  config:
    #事物拦截SMO层的bean名称匹配
    beanNames: "*SMO,*SMOImpl,*Service,*ServiceImpl"
    #事物拦截SMO层的方法名称匹配
    methods:
      get*: PROPAGATION_REQUIRED,-Exception,readOnly
      query*: PROPAGATION_REQUIRED,-Exception,readOnly
      add*: PROPAGATION_REQUIRED
      save*: PROPAGATION_REQUIRED
      update*: PROPAGATION_REQUIRED
      delete*: PROPAGATION_REQUIRED
      insert*: PROPAGATION_REQUIRED
      sequence*: PROPAGATION_REQUIRES_NEW