#主配置文件，将框架需要的参数配置在此

#服务端口
server:
  port: 8081

spring:
  cloud:
    refresh:
      #springcloud bug，datasource报循环依赖
      refreshable: none
  application:
    name: service-web
  #激活的配置文件,激活注解@Profile
  profiles:
    active: test,CTCredis
  #spring-boot-admin注册地址
  boot:
    admin:
      client:
        url: http://localhost:8082
  datasource:
    url: jdbc:mysql://10.128.91.198:3306/umcp?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    password: zaq1XSW2

#此处信息用于在spring-boot-admin中展示
info:
  app:
    name: "@project.name@"
    description: "这是一个web工程"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"




## 刷新时，关闭安全验证
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env

mybatis:
  mapperLocations: classpath:com/asiainfo/crm/busi/dao/*.xml


feign:
  #hystrix调用fallback需要加此配置
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #feign调用超时时间，默认是1秒
            timeoutInMilliseconds: 5000

ctgmq:
   config:
     namesrvAuthID: admin
     namesrvAuthPwd: 123456
     namesrvAddr: 10.128.91.222:10000;10.128.91.224:10000;10.128.91.225:10000
     consumerGroupName: dingyuecrm
     producerGroupName: product_hs


#自己根据应用配置的appid修改
app.id: 100003174
# apollo 环境分类
env: DEV
#apollo 本地缓存配置文件目录
apollo.cacheroot: D:\apollo\data